apm-server:
  host: "0.0.0.0:8200"
  shutdown_timeout: 15s
  secret_token: somerandomstring
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
setup.dashboards.enabled: true
setup.kibana:
  host: "kibana:5601"
logging.to_files: false